-- MySQL Script generated by MySQL Workbench
-- Mon Feb 10 02:16:22 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fast_food_stocks
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fast_food_stocks
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fast_food_stocks` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `fast_food_stocks` ;

-- -----------------------------------------------------
-- Table `fast_food_stocks`.`brk-a_cleaned_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast_food_stocks`.`brk-a_cleaned_data` ;

CREATE TABLE IF NOT EXISTS `fast_food_stocks`.`brk-a_cleaned_data` (
  `date` TEXT NULL DEFAULT NULL,
  `open` DOUBLE NULL DEFAULT NULL,
  `high` DOUBLE NULL DEFAULT NULL,
  `low` DOUBLE NULL DEFAULT NULL,
  `close` DOUBLE NULL DEFAULT NULL,
  `adj_close` DOUBLE NULL DEFAULT NULL,
  `volume` BIGINT NULL DEFAULT NULL,
  `daily_return` DOUBLE NULL DEFAULT NULL,
  `ma_7` DOUBLE NULL DEFAULT NULL,
  `ma_30` DOUBLE NULL DEFAULT NULL,
  `volatility_7` DOUBLE NULL DEFAULT NULL,
  `volatility_30` DOUBLE NULL DEFAULT NULL,
  `price_range` DOUBLE NULL DEFAULT NULL,
  `close_lag_1` DOUBLE NULL DEFAULT NULL,
  `close_lag_5` DOUBLE NULL DEFAULT NULL,
  `volume_lag_1` DOUBLE NULL DEFAULT NULL,
  `log_return` DOUBLE NULL DEFAULT NULL,
  `cumulative_return` DOUBLE NULL DEFAULT NULL,
  `rsi` DOUBLE NULL DEFAULT NULL,
  `ma_20` DOUBLE NULL DEFAULT NULL,
  `bb_upper` DOUBLE NULL DEFAULT NULL,
  `bb_lower` DOUBLE NULL DEFAULT NULL,
  `volume_change` DOUBLE NULL DEFAULT NULL,
  `volume_ma_10` DOUBLE NULL DEFAULT NULL,
  `year` BIGINT NULL DEFAULT NULL,
  `month` BIGINT NULL DEFAULT NULL,
  `weekday` BIGINT NULL DEFAULT NULL,
  `day_of_week` TEXT NULL DEFAULT NULL,
  `quarter` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fast_food_stocks`.`dnut_cleaned_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast_food_stocks`.`dnut_cleaned_data` ;

CREATE TABLE IF NOT EXISTS `fast_food_stocks`.`dnut_cleaned_data` (
  `date` TEXT NULL DEFAULT NULL,
  `open` DOUBLE NULL DEFAULT NULL,
  `high` DOUBLE NULL DEFAULT NULL,
  `low` DOUBLE NULL DEFAULT NULL,
  `close` DOUBLE NULL DEFAULT NULL,
  `adj_close` DOUBLE NULL DEFAULT NULL,
  `volume` BIGINT NULL DEFAULT NULL,
  `daily_return` DOUBLE NULL DEFAULT NULL,
  `ma_7` DOUBLE NULL DEFAULT NULL,
  `ma_30` DOUBLE NULL DEFAULT NULL,
  `volatility_7` DOUBLE NULL DEFAULT NULL,
  `volatility_30` DOUBLE NULL DEFAULT NULL,
  `price_range` DOUBLE NULL DEFAULT NULL,
  `close_lag_1` DOUBLE NULL DEFAULT NULL,
  `close_lag_5` DOUBLE NULL DEFAULT NULL,
  `volume_lag_1` DOUBLE NULL DEFAULT NULL,
  `log_return` DOUBLE NULL DEFAULT NULL,
  `cumulative_return` DOUBLE NULL DEFAULT NULL,
  `rsi` DOUBLE NULL DEFAULT NULL,
  `ma_20` DOUBLE NULL DEFAULT NULL,
  `bb_upper` DOUBLE NULL DEFAULT NULL,
  `bb_lower` DOUBLE NULL DEFAULT NULL,
  `volume_change` DOUBLE NULL DEFAULT NULL,
  `volume_ma_10` DOUBLE NULL DEFAULT NULL,
  `year` BIGINT NULL DEFAULT NULL,
  `month` BIGINT NULL DEFAULT NULL,
  `weekday` BIGINT NULL DEFAULT NULL,
  `day_of_week` TEXT NULL DEFAULT NULL,
  `quarter` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fast_food_stocks`.`dpz_cleaned_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast_food_stocks`.`dpz_cleaned_data` ;

CREATE TABLE IF NOT EXISTS `fast_food_stocks`.`dpz_cleaned_data` (
  `date` TEXT NULL DEFAULT NULL,
  `open` DOUBLE NULL DEFAULT NULL,
  `high` DOUBLE NULL DEFAULT NULL,
  `low` DOUBLE NULL DEFAULT NULL,
  `close` DOUBLE NULL DEFAULT NULL,
  `adj_close` DOUBLE NULL DEFAULT NULL,
  `volume` BIGINT NULL DEFAULT NULL,
  `daily_return` DOUBLE NULL DEFAULT NULL,
  `ma_7` DOUBLE NULL DEFAULT NULL,
  `ma_30` DOUBLE NULL DEFAULT NULL,
  `volatility_7` DOUBLE NULL DEFAULT NULL,
  `volatility_30` DOUBLE NULL DEFAULT NULL,
  `price_range` DOUBLE NULL DEFAULT NULL,
  `close_lag_1` DOUBLE NULL DEFAULT NULL,
  `close_lag_5` DOUBLE NULL DEFAULT NULL,
  `volume_lag_1` DOUBLE NULL DEFAULT NULL,
  `log_return` DOUBLE NULL DEFAULT NULL,
  `cumulative_return` DOUBLE NULL DEFAULT NULL,
  `rsi` DOUBLE NULL DEFAULT NULL,
  `ma_20` DOUBLE NULL DEFAULT NULL,
  `bb_upper` DOUBLE NULL DEFAULT NULL,
  `bb_lower` DOUBLE NULL DEFAULT NULL,
  `volume_change` DOUBLE NULL DEFAULT NULL,
  `volume_ma_10` DOUBLE NULL DEFAULT NULL,
  `year` BIGINT NULL DEFAULT NULL,
  `month` BIGINT NULL DEFAULT NULL,
  `weekday` BIGINT NULL DEFAULT NULL,
  `day_of_week` TEXT NULL DEFAULT NULL,
  `quarter` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fast_food_stocks`.`lkncy_cleaned_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast_food_stocks`.`lkncy_cleaned_data` ;

CREATE TABLE IF NOT EXISTS `fast_food_stocks`.`lkncy_cleaned_data` (
  `date` TEXT NULL DEFAULT NULL,
  `open` DOUBLE NULL DEFAULT NULL,
  `high` DOUBLE NULL DEFAULT NULL,
  `low` DOUBLE NULL DEFAULT NULL,
  `close` DOUBLE NULL DEFAULT NULL,
  `adj_close` DOUBLE NULL DEFAULT NULL,
  `volume` BIGINT NULL DEFAULT NULL,
  `daily_return` DOUBLE NULL DEFAULT NULL,
  `ma_7` DOUBLE NULL DEFAULT NULL,
  `ma_30` DOUBLE NULL DEFAULT NULL,
  `volatility_7` DOUBLE NULL DEFAULT NULL,
  `volatility_30` DOUBLE NULL DEFAULT NULL,
  `price_range` DOUBLE NULL DEFAULT NULL,
  `close_lag_1` DOUBLE NULL DEFAULT NULL,
  `close_lag_5` DOUBLE NULL DEFAULT NULL,
  `volume_lag_1` DOUBLE NULL DEFAULT NULL,
  `log_return` DOUBLE NULL DEFAULT NULL,
  `cumulative_return` DOUBLE NULL DEFAULT NULL,
  `rsi` DOUBLE NULL DEFAULT NULL,
  `ma_20` DOUBLE NULL DEFAULT NULL,
  `bb_upper` DOUBLE NULL DEFAULT NULL,
  `bb_lower` DOUBLE NULL DEFAULT NULL,
  `volume_change` DOUBLE NULL DEFAULT NULL,
  `volume_ma_10` DOUBLE NULL DEFAULT NULL,
  `year` BIGINT NULL DEFAULT NULL,
  `month` BIGINT NULL DEFAULT NULL,
  `weekday` BIGINT NULL DEFAULT NULL,
  `day_of_week` TEXT NULL DEFAULT NULL,
  `quarter` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fast_food_stocks`.`mcd_cleaned_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast_food_stocks`.`mcd_cleaned_data` ;

CREATE TABLE IF NOT EXISTS `fast_food_stocks`.`mcd_cleaned_data` (
  `date` TEXT NULL DEFAULT NULL,
  `open` DOUBLE NULL DEFAULT NULL,
  `high` DOUBLE NULL DEFAULT NULL,
  `low` DOUBLE NULL DEFAULT NULL,
  `close` DOUBLE NULL DEFAULT NULL,
  `adj_close` DOUBLE NULL DEFAULT NULL,
  `volume` BIGINT NULL DEFAULT NULL,
  `daily_return` DOUBLE NULL DEFAULT NULL,
  `ma_7` DOUBLE NULL DEFAULT NULL,
  `ma_30` DOUBLE NULL DEFAULT NULL,
  `volatility_7` DOUBLE NULL DEFAULT NULL,
  `volatility_30` DOUBLE NULL DEFAULT NULL,
  `price_range` DOUBLE NULL DEFAULT NULL,
  `close_lag_1` DOUBLE NULL DEFAULT NULL,
  `close_lag_5` DOUBLE NULL DEFAULT NULL,
  `volume_lag_1` DOUBLE NULL DEFAULT NULL,
  `log_return` DOUBLE NULL DEFAULT NULL,
  `cumulative_return` DOUBLE NULL DEFAULT NULL,
  `rsi` DOUBLE NULL DEFAULT NULL,
  `ma_20` DOUBLE NULL DEFAULT NULL,
  `bb_upper` DOUBLE NULL DEFAULT NULL,
  `bb_lower` DOUBLE NULL DEFAULT NULL,
  `volume_change` DOUBLE NULL DEFAULT NULL,
  `volume_ma_10` DOUBLE NULL DEFAULT NULL,
  `year` BIGINT NULL DEFAULT NULL,
  `month` BIGINT NULL DEFAULT NULL,
  `weekday` BIGINT NULL DEFAULT NULL,
  `day_of_week` TEXT NULL DEFAULT NULL,
  `quarter` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fast_food_stocks`.`pzza_cleaned_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast_food_stocks`.`pzza_cleaned_data` ;

CREATE TABLE IF NOT EXISTS `fast_food_stocks`.`pzza_cleaned_data` (
  `date` TEXT NULL DEFAULT NULL,
  `open` DOUBLE NULL DEFAULT NULL,
  `high` DOUBLE NULL DEFAULT NULL,
  `low` DOUBLE NULL DEFAULT NULL,
  `close` DOUBLE NULL DEFAULT NULL,
  `adj_close` DOUBLE NULL DEFAULT NULL,
  `volume` BIGINT NULL DEFAULT NULL,
  `daily_return` DOUBLE NULL DEFAULT NULL,
  `ma_7` DOUBLE NULL DEFAULT NULL,
  `ma_30` DOUBLE NULL DEFAULT NULL,
  `volatility_7` DOUBLE NULL DEFAULT NULL,
  `volatility_30` DOUBLE NULL DEFAULT NULL,
  `price_range` DOUBLE NULL DEFAULT NULL,
  `close_lag_1` DOUBLE NULL DEFAULT NULL,
  `close_lag_5` DOUBLE NULL DEFAULT NULL,
  `volume_lag_1` DOUBLE NULL DEFAULT NULL,
  `log_return` DOUBLE NULL DEFAULT NULL,
  `cumulative_return` DOUBLE NULL DEFAULT NULL,
  `rsi` DOUBLE NULL DEFAULT NULL,
  `ma_20` DOUBLE NULL DEFAULT NULL,
  `bb_upper` DOUBLE NULL DEFAULT NULL,
  `bb_lower` DOUBLE NULL DEFAULT NULL,
  `volume_change` DOUBLE NULL DEFAULT NULL,
  `volume_ma_10` DOUBLE NULL DEFAULT NULL,
  `year` BIGINT NULL DEFAULT NULL,
  `month` BIGINT NULL DEFAULT NULL,
  `weekday` BIGINT NULL DEFAULT NULL,
  `day_of_week` TEXT NULL DEFAULT NULL,
  `quarter` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fast_food_stocks`.`qsr_cleaned_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast_food_stocks`.`qsr_cleaned_data` ;

CREATE TABLE IF NOT EXISTS `fast_food_stocks`.`qsr_cleaned_data` (
  `date` TEXT NULL DEFAULT NULL,
  `open` DOUBLE NULL DEFAULT NULL,
  `high` DOUBLE NULL DEFAULT NULL,
  `low` DOUBLE NULL DEFAULT NULL,
  `close` DOUBLE NULL DEFAULT NULL,
  `adj_close` DOUBLE NULL DEFAULT NULL,
  `volume` BIGINT NULL DEFAULT NULL,
  `daily_return` DOUBLE NULL DEFAULT NULL,
  `ma_7` DOUBLE NULL DEFAULT NULL,
  `ma_30` DOUBLE NULL DEFAULT NULL,
  `volatility_7` DOUBLE NULL DEFAULT NULL,
  `volatility_30` DOUBLE NULL DEFAULT NULL,
  `price_range` DOUBLE NULL DEFAULT NULL,
  `close_lag_1` DOUBLE NULL DEFAULT NULL,
  `close_lag_5` DOUBLE NULL DEFAULT NULL,
  `volume_lag_1` DOUBLE NULL DEFAULT NULL,
  `log_return` DOUBLE NULL DEFAULT NULL,
  `cumulative_return` DOUBLE NULL DEFAULT NULL,
  `rsi` DOUBLE NULL DEFAULT NULL,
  `ma_20` DOUBLE NULL DEFAULT NULL,
  `bb_upper` DOUBLE NULL DEFAULT NULL,
  `bb_lower` DOUBLE NULL DEFAULT NULL,
  `volume_change` DOUBLE NULL DEFAULT NULL,
  `volume_ma_10` DOUBLE NULL DEFAULT NULL,
  `year` BIGINT NULL DEFAULT NULL,
  `month` BIGINT NULL DEFAULT NULL,
  `weekday` BIGINT NULL DEFAULT NULL,
  `day_of_week` TEXT NULL DEFAULT NULL,
  `quarter` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fast_food_stocks`.`sbux_cleaned_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast_food_stocks`.`sbux_cleaned_data` ;

CREATE TABLE IF NOT EXISTS `fast_food_stocks`.`sbux_cleaned_data` (
  `date` TEXT NULL DEFAULT NULL,
  `open` DOUBLE NULL DEFAULT NULL,
  `high` DOUBLE NULL DEFAULT NULL,
  `low` DOUBLE NULL DEFAULT NULL,
  `close` DOUBLE NULL DEFAULT NULL,
  `adj_close` DOUBLE NULL DEFAULT NULL,
  `volume` BIGINT NULL DEFAULT NULL,
  `daily_return` DOUBLE NULL DEFAULT NULL,
  `ma_7` DOUBLE NULL DEFAULT NULL,
  `ma_30` DOUBLE NULL DEFAULT NULL,
  `volatility_7` DOUBLE NULL DEFAULT NULL,
  `volatility_30` DOUBLE NULL DEFAULT NULL,
  `price_range` DOUBLE NULL DEFAULT NULL,
  `close_lag_1` DOUBLE NULL DEFAULT NULL,
  `close_lag_5` DOUBLE NULL DEFAULT NULL,
  `volume_lag_1` DOUBLE NULL DEFAULT NULL,
  `log_return` DOUBLE NULL DEFAULT NULL,
  `cumulative_return` DOUBLE NULL DEFAULT NULL,
  `rsi` DOUBLE NULL DEFAULT NULL,
  `ma_20` DOUBLE NULL DEFAULT NULL,
  `bb_upper` DOUBLE NULL DEFAULT NULL,
  `bb_lower` DOUBLE NULL DEFAULT NULL,
  `volume_change` DOUBLE NULL DEFAULT NULL,
  `volume_ma_10` DOUBLE NULL DEFAULT NULL,
  `year` BIGINT NULL DEFAULT NULL,
  `month` BIGINT NULL DEFAULT NULL,
  `weekday` BIGINT NULL DEFAULT NULL,
  `day_of_week` TEXT NULL DEFAULT NULL,
  `quarter` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fast_food_stocks`.`wen_cleaned_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast_food_stocks`.`wen_cleaned_data` ;

CREATE TABLE IF NOT EXISTS `fast_food_stocks`.`wen_cleaned_data` (
  `date` TEXT NULL DEFAULT NULL,
  `open` DOUBLE NULL DEFAULT NULL,
  `high` DOUBLE NULL DEFAULT NULL,
  `low` DOUBLE NULL DEFAULT NULL,
  `close` DOUBLE NULL DEFAULT NULL,
  `adj_close` DOUBLE NULL DEFAULT NULL,
  `volume` BIGINT NULL DEFAULT NULL,
  `daily_return` DOUBLE NULL DEFAULT NULL,
  `ma_7` DOUBLE NULL DEFAULT NULL,
  `ma_30` DOUBLE NULL DEFAULT NULL,
  `volatility_7` DOUBLE NULL DEFAULT NULL,
  `volatility_30` DOUBLE NULL DEFAULT NULL,
  `price_range` DOUBLE NULL DEFAULT NULL,
  `close_lag_1` DOUBLE NULL DEFAULT NULL,
  `close_lag_5` DOUBLE NULL DEFAULT NULL,
  `volume_lag_1` DOUBLE NULL DEFAULT NULL,
  `log_return` DOUBLE NULL DEFAULT NULL,
  `cumulative_return` DOUBLE NULL DEFAULT NULL,
  `rsi` DOUBLE NULL DEFAULT NULL,
  `ma_20` DOUBLE NULL DEFAULT NULL,
  `bb_upper` DOUBLE NULL DEFAULT NULL,
  `bb_lower` DOUBLE NULL DEFAULT NULL,
  `volume_change` DOUBLE NULL DEFAULT NULL,
  `volume_ma_10` DOUBLE NULL DEFAULT NULL,
  `year` BIGINT NULL DEFAULT NULL,
  `month` BIGINT NULL DEFAULT NULL,
  `weekday` BIGINT NULL DEFAULT NULL,
  `day_of_week` TEXT NULL DEFAULT NULL,
  `quarter` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fast_food_stocks`.`yum_cleaned_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fast_food_stocks`.`yum_cleaned_data` ;

CREATE TABLE IF NOT EXISTS `fast_food_stocks`.`yum_cleaned_data` (
  `date` TEXT NULL DEFAULT NULL,
  `open` DOUBLE NULL DEFAULT NULL,
  `high` DOUBLE NULL DEFAULT NULL,
  `low` DOUBLE NULL DEFAULT NULL,
  `close` DOUBLE NULL DEFAULT NULL,
  `adj_close` DOUBLE NULL DEFAULT NULL,
  `volume` BIGINT NULL DEFAULT NULL,
  `daily_return` DOUBLE NULL DEFAULT NULL,
  `ma_7` DOUBLE NULL DEFAULT NULL,
  `ma_30` DOUBLE NULL DEFAULT NULL,
  `volatility_7` DOUBLE NULL DEFAULT NULL,
  `volatility_30` DOUBLE NULL DEFAULT NULL,
  `price_range` DOUBLE NULL DEFAULT NULL,
  `close_lag_1` DOUBLE NULL DEFAULT NULL,
  `close_lag_5` DOUBLE NULL DEFAULT NULL,
  `volume_lag_1` DOUBLE NULL DEFAULT NULL,
  `log_return` DOUBLE NULL DEFAULT NULL,
  `cumulative_return` DOUBLE NULL DEFAULT NULL,
  `rsi` DOUBLE NULL DEFAULT NULL,
  `ma_20` DOUBLE NULL DEFAULT NULL,
  `bb_upper` DOUBLE NULL DEFAULT NULL,
  `bb_lower` DOUBLE NULL DEFAULT NULL,
  `volume_change` DOUBLE NULL DEFAULT NULL,
  `volume_ma_10` DOUBLE NULL DEFAULT NULL,
  `year` BIGINT NULL DEFAULT NULL,
  `month` BIGINT NULL DEFAULT NULL,
  `weekday` BIGINT NULL DEFAULT NULL,
  `day_of_week` TEXT NULL DEFAULT NULL,
  `quarter` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
